// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: getNeighbors.proto

package org.dbscan;

public final class getNeighbors {
  private getNeighbors() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface getNeighborsRequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string data = 1;
    /**
     * <code>required string data = 1;</code>
     */
    boolean hasData();
    /**
     * <code>required string data = 1;</code>
     */
    java.lang.String getData();
    /**
     * <code>required string data = 1;</code>
     */
    com.google.protobuf.ByteString
        getDataBytes();
  }
  /**
   * Protobuf type {@code getNeighborsRequest}
   */
  public static final class getNeighborsRequest extends
      com.google.protobuf.GeneratedMessage
      implements getNeighborsRequestOrBuilder {
    // Use getNeighborsRequest.newBuilder() to construct.
    private getNeighborsRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private getNeighborsRequest(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final getNeighborsRequest defaultInstance;
    public static getNeighborsRequest getDefaultInstance() {
      return defaultInstance;
    }

    public getNeighborsRequest getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private getNeighborsRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              data_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.dbscan.getNeighbors.internal_static_getNeighborsRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.dbscan.getNeighbors.internal_static_getNeighborsRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.dbscan.getNeighbors.getNeighborsRequest.class, org.dbscan.getNeighbors.getNeighborsRequest.Builder.class);
    }

    public static com.google.protobuf.Parser<getNeighborsRequest> PARSER =
        new com.google.protobuf.AbstractParser<getNeighborsRequest>() {
      public getNeighborsRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new getNeighborsRequest(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<getNeighborsRequest> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string data = 1;
    public static final int DATA_FIELD_NUMBER = 1;
    private java.lang.Object data_;
    /**
     * <code>required string data = 1;</code>
     */
    public boolean hasData() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string data = 1;</code>
     */
    public java.lang.String getData() {
      java.lang.Object ref = data_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          data_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string data = 1;</code>
     */
    public com.google.protobuf.ByteString
        getDataBytes() {
      java.lang.Object ref = data_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        data_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      data_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasData()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getDataBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getDataBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.dbscan.getNeighbors.getNeighborsRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.dbscan.getNeighbors.getNeighborsRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.dbscan.getNeighbors.getNeighborsRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.dbscan.getNeighbors.getNeighborsRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.dbscan.getNeighbors.getNeighborsRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.dbscan.getNeighbors.getNeighborsRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.dbscan.getNeighbors.getNeighborsRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.dbscan.getNeighbors.getNeighborsRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.dbscan.getNeighbors.getNeighborsRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.dbscan.getNeighbors.getNeighborsRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.dbscan.getNeighbors.getNeighborsRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code getNeighborsRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.dbscan.getNeighbors.getNeighborsRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.dbscan.getNeighbors.internal_static_getNeighborsRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.dbscan.getNeighbors.internal_static_getNeighborsRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.dbscan.getNeighbors.getNeighborsRequest.class, org.dbscan.getNeighbors.getNeighborsRequest.Builder.class);
      }

      // Construct using org.dbscan.getNeighbors.getNeighborsRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        data_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.dbscan.getNeighbors.internal_static_getNeighborsRequest_descriptor;
      }

      public org.dbscan.getNeighbors.getNeighborsRequest getDefaultInstanceForType() {
        return org.dbscan.getNeighbors.getNeighborsRequest.getDefaultInstance();
      }

      public org.dbscan.getNeighbors.getNeighborsRequest build() {
        org.dbscan.getNeighbors.getNeighborsRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.dbscan.getNeighbors.getNeighborsRequest buildPartial() {
        org.dbscan.getNeighbors.getNeighborsRequest result = new org.dbscan.getNeighbors.getNeighborsRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.data_ = data_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.dbscan.getNeighbors.getNeighborsRequest) {
          return mergeFrom((org.dbscan.getNeighbors.getNeighborsRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.dbscan.getNeighbors.getNeighborsRequest other) {
        if (other == org.dbscan.getNeighbors.getNeighborsRequest.getDefaultInstance()) return this;
        if (other.hasData()) {
          bitField0_ |= 0x00000001;
          data_ = other.data_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasData()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.dbscan.getNeighbors.getNeighborsRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.dbscan.getNeighbors.getNeighborsRequest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string data = 1;
      private java.lang.Object data_ = "";
      /**
       * <code>required string data = 1;</code>
       */
      public boolean hasData() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string data = 1;</code>
       */
      public java.lang.String getData() {
        java.lang.Object ref = data_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          data_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string data = 1;</code>
       */
      public com.google.protobuf.ByteString
          getDataBytes() {
        java.lang.Object ref = data_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          data_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string data = 1;</code>
       */
      public Builder setData(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string data = 1;</code>
       */
      public Builder clearData() {
        bitField0_ = (bitField0_ & ~0x00000001);
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }
      /**
       * <code>required string data = 1;</code>
       */
      public Builder setDataBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        data_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:getNeighborsRequest)
    }

    static {
      defaultInstance = new getNeighborsRequest(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:getNeighborsRequest)
  }

  public interface getNeighborsResponseOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated string datas = 1;
    /**
     * <code>repeated string datas = 1;</code>
     */
    java.util.List<java.lang.String>
    getDatasList();
    /**
     * <code>repeated string datas = 1;</code>
     */
    int getDatasCount();
    /**
     * <code>repeated string datas = 1;</code>
     */
    java.lang.String getDatas(int index);
    /**
     * <code>repeated string datas = 1;</code>
     */
    com.google.protobuf.ByteString
        getDatasBytes(int index);
  }
  /**
   * Protobuf type {@code getNeighborsResponse}
   */
  public static final class getNeighborsResponse extends
      com.google.protobuf.GeneratedMessage
      implements getNeighborsResponseOrBuilder {
    // Use getNeighborsResponse.newBuilder() to construct.
    private getNeighborsResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private getNeighborsResponse(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final getNeighborsResponse defaultInstance;
    public static getNeighborsResponse getDefaultInstance() {
      return defaultInstance;
    }

    public getNeighborsResponse getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private getNeighborsResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                datas_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000001;
              }
              datas_.add(input.readBytes());
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          datas_ = new com.google.protobuf.UnmodifiableLazyStringList(datas_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.dbscan.getNeighbors.internal_static_getNeighborsResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.dbscan.getNeighbors.internal_static_getNeighborsResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.dbscan.getNeighbors.getNeighborsResponse.class, org.dbscan.getNeighbors.getNeighborsResponse.Builder.class);
    }

    public static com.google.protobuf.Parser<getNeighborsResponse> PARSER =
        new com.google.protobuf.AbstractParser<getNeighborsResponse>() {
      public getNeighborsResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new getNeighborsResponse(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<getNeighborsResponse> getParserForType() {
      return PARSER;
    }

    // repeated string datas = 1;
    public static final int DATAS_FIELD_NUMBER = 1;
    private com.google.protobuf.LazyStringList datas_;
    /**
     * <code>repeated string datas = 1;</code>
     */
    public java.util.List<java.lang.String>
        getDatasList() {
      return datas_;
    }
    /**
     * <code>repeated string datas = 1;</code>
     */
    public int getDatasCount() {
      return datas_.size();
    }
    /**
     * <code>repeated string datas = 1;</code>
     */
    public java.lang.String getDatas(int index) {
      return datas_.get(index);
    }
    /**
     * <code>repeated string datas = 1;</code>
     */
    public com.google.protobuf.ByteString
        getDatasBytes(int index) {
      return datas_.getByteString(index);
    }

    private void initFields() {
      datas_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < datas_.size(); i++) {
        output.writeBytes(1, datas_.getByteString(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < datas_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(datas_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getDatasList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.dbscan.getNeighbors.getNeighborsResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.dbscan.getNeighbors.getNeighborsResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.dbscan.getNeighbors.getNeighborsResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.dbscan.getNeighbors.getNeighborsResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.dbscan.getNeighbors.getNeighborsResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.dbscan.getNeighbors.getNeighborsResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.dbscan.getNeighbors.getNeighborsResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.dbscan.getNeighbors.getNeighborsResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.dbscan.getNeighbors.getNeighborsResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.dbscan.getNeighbors.getNeighborsResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.dbscan.getNeighbors.getNeighborsResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code getNeighborsResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.dbscan.getNeighbors.getNeighborsResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.dbscan.getNeighbors.internal_static_getNeighborsResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.dbscan.getNeighbors.internal_static_getNeighborsResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.dbscan.getNeighbors.getNeighborsResponse.class, org.dbscan.getNeighbors.getNeighborsResponse.Builder.class);
      }

      // Construct using org.dbscan.getNeighbors.getNeighborsResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        datas_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.dbscan.getNeighbors.internal_static_getNeighborsResponse_descriptor;
      }

      public org.dbscan.getNeighbors.getNeighborsResponse getDefaultInstanceForType() {
        return org.dbscan.getNeighbors.getNeighborsResponse.getDefaultInstance();
      }

      public org.dbscan.getNeighbors.getNeighborsResponse build() {
        org.dbscan.getNeighbors.getNeighborsResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.dbscan.getNeighbors.getNeighborsResponse buildPartial() {
        org.dbscan.getNeighbors.getNeighborsResponse result = new org.dbscan.getNeighbors.getNeighborsResponse(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          datas_ = new com.google.protobuf.UnmodifiableLazyStringList(
              datas_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.datas_ = datas_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.dbscan.getNeighbors.getNeighborsResponse) {
          return mergeFrom((org.dbscan.getNeighbors.getNeighborsResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.dbscan.getNeighbors.getNeighborsResponse other) {
        if (other == org.dbscan.getNeighbors.getNeighborsResponse.getDefaultInstance()) return this;
        if (!other.datas_.isEmpty()) {
          if (datas_.isEmpty()) {
            datas_ = other.datas_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureDatasIsMutable();
            datas_.addAll(other.datas_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.dbscan.getNeighbors.getNeighborsResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.dbscan.getNeighbors.getNeighborsResponse) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated string datas = 1;
      private com.google.protobuf.LazyStringList datas_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureDatasIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          datas_ = new com.google.protobuf.LazyStringArrayList(datas_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated string datas = 1;</code>
       */
      public java.util.List<java.lang.String>
          getDatasList() {
        return java.util.Collections.unmodifiableList(datas_);
      }
      /**
       * <code>repeated string datas = 1;</code>
       */
      public int getDatasCount() {
        return datas_.size();
      }
      /**
       * <code>repeated string datas = 1;</code>
       */
      public java.lang.String getDatas(int index) {
        return datas_.get(index);
      }
      /**
       * <code>repeated string datas = 1;</code>
       */
      public com.google.protobuf.ByteString
          getDatasBytes(int index) {
        return datas_.getByteString(index);
      }
      /**
       * <code>repeated string datas = 1;</code>
       */
      public Builder setDatas(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureDatasIsMutable();
        datas_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string datas = 1;</code>
       */
      public Builder addDatas(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureDatasIsMutable();
        datas_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string datas = 1;</code>
       */
      public Builder addAllDatas(
          java.lang.Iterable<java.lang.String> values) {
        ensureDatasIsMutable();
        super.addAll(values, datas_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string datas = 1;</code>
       */
      public Builder clearDatas() {
        datas_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string datas = 1;</code>
       */
      public Builder addDatasBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureDatasIsMutable();
        datas_.add(value);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:getNeighborsResponse)
    }

    static {
      defaultInstance = new getNeighborsResponse(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:getNeighborsResponse)
  }

  /**
   * Protobuf service {@code dbscanService}
   */
  public static abstract class dbscanService
      implements com.google.protobuf.Service {
    protected dbscanService() {}

    public interface Interface {
      /**
       * <code>rpc getNeighbours(.getNeighborsRequest) returns (.getNeighborsResponse);</code>
       */
      public abstract void getNeighbours(
          com.google.protobuf.RpcController controller,
          org.dbscan.getNeighbors.getNeighborsRequest request,
          com.google.protobuf.RpcCallback<org.dbscan.getNeighbors.getNeighborsResponse> done);

    }

    public static com.google.protobuf.Service newReflectiveService(
        final Interface impl) {
      return new dbscanService() {
        @java.lang.Override
        public  void getNeighbours(
            com.google.protobuf.RpcController controller,
            org.dbscan.getNeighbors.getNeighborsRequest request,
            com.google.protobuf.RpcCallback<org.dbscan.getNeighbors.getNeighborsResponse> done) {
          impl.getNeighbours(controller, request, done);
        }

      };
    }

    public static com.google.protobuf.BlockingService
        newReflectiveBlockingService(final BlockingInterface impl) {
      return new com.google.protobuf.BlockingService() {
        public final com.google.protobuf.Descriptors.ServiceDescriptor
            getDescriptorForType() {
          return getDescriptor();
        }

        public final com.google.protobuf.Message callBlockingMethod(
            com.google.protobuf.Descriptors.MethodDescriptor method,
            com.google.protobuf.RpcController controller,
            com.google.protobuf.Message request)
            throws com.google.protobuf.ServiceException {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.callBlockingMethod() given method descriptor for " +
              "wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return impl.getNeighbours(controller, (org.dbscan.getNeighbors.getNeighborsRequest)request);
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

        public final com.google.protobuf.Message
            getRequestPrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getRequestPrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return org.dbscan.getNeighbors.getNeighborsRequest.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

        public final com.google.protobuf.Message
            getResponsePrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getResponsePrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return org.dbscan.getNeighbors.getNeighborsResponse.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

      };
    }

    /**
     * <code>rpc getNeighbours(.getNeighborsRequest) returns (.getNeighborsResponse);</code>
     */
    public abstract void getNeighbours(
        com.google.protobuf.RpcController controller,
        org.dbscan.getNeighbors.getNeighborsRequest request,
        com.google.protobuf.RpcCallback<org.dbscan.getNeighbors.getNeighborsResponse> done);

    public static final
        com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptor() {
      return org.dbscan.getNeighbors.getDescriptor().getServices().get(0);
    }
    public final com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }

    public final void callMethod(
        com.google.protobuf.Descriptors.MethodDescriptor method,
        com.google.protobuf.RpcController controller,
        com.google.protobuf.Message request,
        com.google.protobuf.RpcCallback<
          com.google.protobuf.Message> done) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.callMethod() given method descriptor for wrong " +
          "service type.");
      }
      switch(method.getIndex()) {
        case 0:
          this.getNeighbours(controller, (org.dbscan.getNeighbors.getNeighborsRequest)request,
            com.google.protobuf.RpcUtil.<org.dbscan.getNeighbors.getNeighborsResponse>specializeCallback(
              done));
          return;
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public final com.google.protobuf.Message
        getRequestPrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getRequestPrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return org.dbscan.getNeighbors.getNeighborsRequest.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public final com.google.protobuf.Message
        getResponsePrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getResponsePrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return org.dbscan.getNeighbors.getNeighborsResponse.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public static Stub newStub(
        com.google.protobuf.RpcChannel channel) {
      return new Stub(channel);
    }

    public static final class Stub extends org.dbscan.getNeighbors.dbscanService implements Interface {
      private Stub(com.google.protobuf.RpcChannel channel) {
        this.channel = channel;
      }

      private final com.google.protobuf.RpcChannel channel;

      public com.google.protobuf.RpcChannel getChannel() {
        return channel;
      }

      public  void getNeighbours(
          com.google.protobuf.RpcController controller,
          org.dbscan.getNeighbors.getNeighborsRequest request,
          com.google.protobuf.RpcCallback<org.dbscan.getNeighbors.getNeighborsResponse> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          org.dbscan.getNeighbors.getNeighborsResponse.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            org.dbscan.getNeighbors.getNeighborsResponse.class,
            org.dbscan.getNeighbors.getNeighborsResponse.getDefaultInstance()));
      }
    }

    public static BlockingInterface newBlockingStub(
        com.google.protobuf.BlockingRpcChannel channel) {
      return new BlockingStub(channel);
    }

    public interface BlockingInterface {
      public org.dbscan.getNeighbors.getNeighborsResponse getNeighbours(
          com.google.protobuf.RpcController controller,
          org.dbscan.getNeighbors.getNeighborsRequest request)
          throws com.google.protobuf.ServiceException;
    }

    private static final class BlockingStub implements BlockingInterface {
      private BlockingStub(com.google.protobuf.BlockingRpcChannel channel) {
        this.channel = channel;
      }

      private final com.google.protobuf.BlockingRpcChannel channel;

      public org.dbscan.getNeighbors.getNeighborsResponse getNeighbours(
          com.google.protobuf.RpcController controller,
          org.dbscan.getNeighbors.getNeighborsRequest request)
          throws com.google.protobuf.ServiceException {
        return (org.dbscan.getNeighbors.getNeighborsResponse) channel.callBlockingMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          org.dbscan.getNeighbors.getNeighborsResponse.getDefaultInstance());
      }

    }

    // @@protoc_insertion_point(class_scope:dbscanService)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_getNeighborsRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_getNeighborsRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_getNeighborsResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_getNeighborsResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022getNeighbors.proto\"#\n\023getNeighborsRequ" +
      "est\022\014\n\004data\030\001 \002(\t\"%\n\024getNeighborsRespons" +
      "e\022\r\n\005datas\030\001 \003(\t2M\n\rdbscanService\022<\n\rget" +
      "Neighbours\022\024.getNeighborsRequest\032\025.getNe" +
      "ighborsResponseB\037\n\norg.dbscanB\014getNeighb" +
      "orsH\001\210\001\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_getNeighborsRequest_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_getNeighborsRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_getNeighborsRequest_descriptor,
              new java.lang.String[] { "Data", });
          internal_static_getNeighborsResponse_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_getNeighborsResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_getNeighborsResponse_descriptor,
              new java.lang.String[] { "Datas", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
