// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: getNeighbors.proto

package org.dbscan;

public final class getNeighbors {
  private getNeighbors() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface getNeighborsRequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required double Eps = 1 [default = 1];
    /**
     * <code>required double Eps = 1 [default = 1];</code>
     */
    boolean hasEps();
    /**
     * <code>required double Eps = 1 [default = 1];</code>
     */
    double getEps();

    // repeated double data = 2;
    /**
     * <code>repeated double data = 2;</code>
     */
    java.util.List<java.lang.Double> getDataList();
    /**
     * <code>repeated double data = 2;</code>
     */
    int getDataCount();
    /**
     * <code>repeated double data = 2;</code>
     */
    double getData(int index);
  }
  /**
   * Protobuf type {@code getNeighborsRequest}
   */
  public static final class getNeighborsRequest extends
      com.google.protobuf.GeneratedMessage
      implements getNeighborsRequestOrBuilder {
    // Use getNeighborsRequest.newBuilder() to construct.
    private getNeighborsRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private getNeighborsRequest(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final getNeighborsRequest defaultInstance;
    public static getNeighborsRequest getDefaultInstance() {
      return defaultInstance;
    }

    public getNeighborsRequest getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private getNeighborsRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 9: {
              bitField0_ |= 0x00000001;
              eps_ = input.readDouble();
              break;
            }
            case 17: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                data_ = new java.util.ArrayList<java.lang.Double>();
                mutable_bitField0_ |= 0x00000002;
              }
              data_.add(input.readDouble());
              break;
            }
            case 18: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002) && input.getBytesUntilLimit() > 0) {
                data_ = new java.util.ArrayList<java.lang.Double>();
                mutable_bitField0_ |= 0x00000002;
              }
              while (input.getBytesUntilLimit() > 0) {
                data_.add(input.readDouble());
              }
              input.popLimit(limit);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          data_ = java.util.Collections.unmodifiableList(data_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.dbscan.getNeighbors.internal_static_getNeighborsRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.dbscan.getNeighbors.internal_static_getNeighborsRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.dbscan.getNeighbors.getNeighborsRequest.class, org.dbscan.getNeighbors.getNeighborsRequest.Builder.class);
    }

    public static com.google.protobuf.Parser<getNeighborsRequest> PARSER =
        new com.google.protobuf.AbstractParser<getNeighborsRequest>() {
      public getNeighborsRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new getNeighborsRequest(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<getNeighborsRequest> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required double Eps = 1 [default = 1];
    public static final int EPS_FIELD_NUMBER = 1;
    private double eps_;
    /**
     * <code>required double Eps = 1 [default = 1];</code>
     */
    public boolean hasEps() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required double Eps = 1 [default = 1];</code>
     */
    public double getEps() {
      return eps_;
    }

    // repeated double data = 2;
    public static final int DATA_FIELD_NUMBER = 2;
    private java.util.List<java.lang.Double> data_;
    /**
     * <code>repeated double data = 2;</code>
     */
    public java.util.List<java.lang.Double>
        getDataList() {
      return data_;
    }
    /**
     * <code>repeated double data = 2;</code>
     */
    public int getDataCount() {
      return data_.size();
    }
    /**
     * <code>repeated double data = 2;</code>
     */
    public double getData(int index) {
      return data_.get(index);
    }

    private void initFields() {
      eps_ = 1D;
      data_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasEps()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeDouble(1, eps_);
      }
      for (int i = 0; i < data_.size(); i++) {
        output.writeDouble(2, data_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(1, eps_);
      }
      {
        int dataSize = 0;
        dataSize = 8 * getDataList().size();
        size += dataSize;
        size += 1 * getDataList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.dbscan.getNeighbors.getNeighborsRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.dbscan.getNeighbors.getNeighborsRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.dbscan.getNeighbors.getNeighborsRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.dbscan.getNeighbors.getNeighborsRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.dbscan.getNeighbors.getNeighborsRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.dbscan.getNeighbors.getNeighborsRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.dbscan.getNeighbors.getNeighborsRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.dbscan.getNeighbors.getNeighborsRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.dbscan.getNeighbors.getNeighborsRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.dbscan.getNeighbors.getNeighborsRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.dbscan.getNeighbors.getNeighborsRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code getNeighborsRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.dbscan.getNeighbors.getNeighborsRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.dbscan.getNeighbors.internal_static_getNeighborsRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.dbscan.getNeighbors.internal_static_getNeighborsRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.dbscan.getNeighbors.getNeighborsRequest.class, org.dbscan.getNeighbors.getNeighborsRequest.Builder.class);
      }

      // Construct using org.dbscan.getNeighbors.getNeighborsRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        eps_ = 1D;
        bitField0_ = (bitField0_ & ~0x00000001);
        data_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.dbscan.getNeighbors.internal_static_getNeighborsRequest_descriptor;
      }

      public org.dbscan.getNeighbors.getNeighborsRequest getDefaultInstanceForType() {
        return org.dbscan.getNeighbors.getNeighborsRequest.getDefaultInstance();
      }

      public org.dbscan.getNeighbors.getNeighborsRequest build() {
        org.dbscan.getNeighbors.getNeighborsRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.dbscan.getNeighbors.getNeighborsRequest buildPartial() {
        org.dbscan.getNeighbors.getNeighborsRequest result = new org.dbscan.getNeighbors.getNeighborsRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.eps_ = eps_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          data_ = java.util.Collections.unmodifiableList(data_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.data_ = data_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.dbscan.getNeighbors.getNeighborsRequest) {
          return mergeFrom((org.dbscan.getNeighbors.getNeighborsRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.dbscan.getNeighbors.getNeighborsRequest other) {
        if (other == org.dbscan.getNeighbors.getNeighborsRequest.getDefaultInstance()) return this;
        if (other.hasEps()) {
          setEps(other.getEps());
        }
        if (!other.data_.isEmpty()) {
          if (data_.isEmpty()) {
            data_ = other.data_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureDataIsMutable();
            data_.addAll(other.data_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasEps()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.dbscan.getNeighbors.getNeighborsRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.dbscan.getNeighbors.getNeighborsRequest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required double Eps = 1 [default = 1];
      private double eps_ = 1D;
      /**
       * <code>required double Eps = 1 [default = 1];</code>
       */
      public boolean hasEps() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required double Eps = 1 [default = 1];</code>
       */
      public double getEps() {
        return eps_;
      }
      /**
       * <code>required double Eps = 1 [default = 1];</code>
       */
      public Builder setEps(double value) {
        bitField0_ |= 0x00000001;
        eps_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required double Eps = 1 [default = 1];</code>
       */
      public Builder clearEps() {
        bitField0_ = (bitField0_ & ~0x00000001);
        eps_ = 1D;
        onChanged();
        return this;
      }

      // repeated double data = 2;
      private java.util.List<java.lang.Double> data_ = java.util.Collections.emptyList();
      private void ensureDataIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          data_ = new java.util.ArrayList<java.lang.Double>(data_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated double data = 2;</code>
       */
      public java.util.List<java.lang.Double>
          getDataList() {
        return java.util.Collections.unmodifiableList(data_);
      }
      /**
       * <code>repeated double data = 2;</code>
       */
      public int getDataCount() {
        return data_.size();
      }
      /**
       * <code>repeated double data = 2;</code>
       */
      public double getData(int index) {
        return data_.get(index);
      }
      /**
       * <code>repeated double data = 2;</code>
       */
      public Builder setData(
          int index, double value) {
        ensureDataIsMutable();
        data_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated double data = 2;</code>
       */
      public Builder addData(double value) {
        ensureDataIsMutable();
        data_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated double data = 2;</code>
       */
      public Builder addAllData(
          java.lang.Iterable<? extends java.lang.Double> values) {
        ensureDataIsMutable();
        super.addAll(values, data_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated double data = 2;</code>
       */
      public Builder clearData() {
        data_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:getNeighborsRequest)
    }

    static {
      defaultInstance = new getNeighborsRequest(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:getNeighborsRequest)
  }

  public interface DataOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string rowkey = 1;
    /**
     * <code>required string rowkey = 1;</code>
     */
    boolean hasRowkey();
    /**
     * <code>required string rowkey = 1;</code>
     */
    java.lang.String getRowkey();
    /**
     * <code>required string rowkey = 1;</code>
     */
    com.google.protobuf.ByteString
        getRowkeyBytes();

    // repeated double point = 2;
    /**
     * <code>repeated double point = 2;</code>
     */
    java.util.List<java.lang.Double> getPointList();
    /**
     * <code>repeated double point = 2;</code>
     */
    int getPointCount();
    /**
     * <code>repeated double point = 2;</code>
     */
    double getPoint(int index);

    // required int32 clusterid = 3 [default = 0];
    /**
     * <code>required int32 clusterid = 3 [default = 0];</code>
     */
    boolean hasClusterid();
    /**
     * <code>required int32 clusterid = 3 [default = 0];</code>
     */
    int getClusterid();

    // required int32 numOfNeighbors = 4 [default = 1];
    /**
     * <code>required int32 numOfNeighbors = 4 [default = 1];</code>
     */
    boolean hasNumOfNeighbors();
    /**
     * <code>required int32 numOfNeighbors = 4 [default = 1];</code>
     */
    int getNumOfNeighbors();
  }
  /**
   * Protobuf type {@code Data}
   */
  public static final class Data extends
      com.google.protobuf.GeneratedMessage
      implements DataOrBuilder {
    // Use Data.newBuilder() to construct.
    private Data(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Data(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Data defaultInstance;
    public static Data getDefaultInstance() {
      return defaultInstance;
    }

    public Data getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Data(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              rowkey_ = input.readBytes();
              break;
            }
            case 17: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                point_ = new java.util.ArrayList<java.lang.Double>();
                mutable_bitField0_ |= 0x00000002;
              }
              point_.add(input.readDouble());
              break;
            }
            case 18: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002) && input.getBytesUntilLimit() > 0) {
                point_ = new java.util.ArrayList<java.lang.Double>();
                mutable_bitField0_ |= 0x00000002;
              }
              while (input.getBytesUntilLimit() > 0) {
                point_.add(input.readDouble());
              }
              input.popLimit(limit);
              break;
            }
            case 24: {
              bitField0_ |= 0x00000002;
              clusterid_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000004;
              numOfNeighbors_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          point_ = java.util.Collections.unmodifiableList(point_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.dbscan.getNeighbors.internal_static_Data_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.dbscan.getNeighbors.internal_static_Data_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.dbscan.getNeighbors.Data.class, org.dbscan.getNeighbors.Data.Builder.class);
    }

    public static com.google.protobuf.Parser<Data> PARSER =
        new com.google.protobuf.AbstractParser<Data>() {
      public Data parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Data(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Data> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string rowkey = 1;
    public static final int ROWKEY_FIELD_NUMBER = 1;
    private java.lang.Object rowkey_;
    /**
     * <code>required string rowkey = 1;</code>
     */
    public boolean hasRowkey() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string rowkey = 1;</code>
     */
    public java.lang.String getRowkey() {
      java.lang.Object ref = rowkey_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          rowkey_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string rowkey = 1;</code>
     */
    public com.google.protobuf.ByteString
        getRowkeyBytes() {
      java.lang.Object ref = rowkey_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        rowkey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // repeated double point = 2;
    public static final int POINT_FIELD_NUMBER = 2;
    private java.util.List<java.lang.Double> point_;
    /**
     * <code>repeated double point = 2;</code>
     */
    public java.util.List<java.lang.Double>
        getPointList() {
      return point_;
    }
    /**
     * <code>repeated double point = 2;</code>
     */
    public int getPointCount() {
      return point_.size();
    }
    /**
     * <code>repeated double point = 2;</code>
     */
    public double getPoint(int index) {
      return point_.get(index);
    }

    // required int32 clusterid = 3 [default = 0];
    public static final int CLUSTERID_FIELD_NUMBER = 3;
    private int clusterid_;
    /**
     * <code>required int32 clusterid = 3 [default = 0];</code>
     */
    public boolean hasClusterid() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 clusterid = 3 [default = 0];</code>
     */
    public int getClusterid() {
      return clusterid_;
    }

    // required int32 numOfNeighbors = 4 [default = 1];
    public static final int NUMOFNEIGHBORS_FIELD_NUMBER = 4;
    private int numOfNeighbors_;
    /**
     * <code>required int32 numOfNeighbors = 4 [default = 1];</code>
     */
    public boolean hasNumOfNeighbors() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int32 numOfNeighbors = 4 [default = 1];</code>
     */
    public int getNumOfNeighbors() {
      return numOfNeighbors_;
    }

    private void initFields() {
      rowkey_ = "";
      point_ = java.util.Collections.emptyList();
      clusterid_ = 0;
      numOfNeighbors_ = 1;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasRowkey()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasClusterid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasNumOfNeighbors()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getRowkeyBytes());
      }
      for (int i = 0; i < point_.size(); i++) {
        output.writeDouble(2, point_.get(i));
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(3, clusterid_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(4, numOfNeighbors_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getRowkeyBytes());
      }
      {
        int dataSize = 0;
        dataSize = 8 * getPointList().size();
        size += dataSize;
        size += 1 * getPointList().size();
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, clusterid_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, numOfNeighbors_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.dbscan.getNeighbors.Data parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.dbscan.getNeighbors.Data parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.dbscan.getNeighbors.Data parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.dbscan.getNeighbors.Data parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.dbscan.getNeighbors.Data parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.dbscan.getNeighbors.Data parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.dbscan.getNeighbors.Data parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.dbscan.getNeighbors.Data parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.dbscan.getNeighbors.Data parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.dbscan.getNeighbors.Data parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.dbscan.getNeighbors.Data prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Data}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.dbscan.getNeighbors.DataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.dbscan.getNeighbors.internal_static_Data_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.dbscan.getNeighbors.internal_static_Data_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.dbscan.getNeighbors.Data.class, org.dbscan.getNeighbors.Data.Builder.class);
      }

      // Construct using org.dbscan.getNeighbors.Data.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        rowkey_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        point_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        clusterid_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        numOfNeighbors_ = 1;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.dbscan.getNeighbors.internal_static_Data_descriptor;
      }

      public org.dbscan.getNeighbors.Data getDefaultInstanceForType() {
        return org.dbscan.getNeighbors.Data.getDefaultInstance();
      }

      public org.dbscan.getNeighbors.Data build() {
        org.dbscan.getNeighbors.Data result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.dbscan.getNeighbors.Data buildPartial() {
        org.dbscan.getNeighbors.Data result = new org.dbscan.getNeighbors.Data(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.rowkey_ = rowkey_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          point_ = java.util.Collections.unmodifiableList(point_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.point_ = point_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000002;
        }
        result.clusterid_ = clusterid_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000004;
        }
        result.numOfNeighbors_ = numOfNeighbors_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.dbscan.getNeighbors.Data) {
          return mergeFrom((org.dbscan.getNeighbors.Data)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.dbscan.getNeighbors.Data other) {
        if (other == org.dbscan.getNeighbors.Data.getDefaultInstance()) return this;
        if (other.hasRowkey()) {
          bitField0_ |= 0x00000001;
          rowkey_ = other.rowkey_;
          onChanged();
        }
        if (!other.point_.isEmpty()) {
          if (point_.isEmpty()) {
            point_ = other.point_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensurePointIsMutable();
            point_.addAll(other.point_);
          }
          onChanged();
        }
        if (other.hasClusterid()) {
          setClusterid(other.getClusterid());
        }
        if (other.hasNumOfNeighbors()) {
          setNumOfNeighbors(other.getNumOfNeighbors());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasRowkey()) {
          
          return false;
        }
        if (!hasClusterid()) {
          
          return false;
        }
        if (!hasNumOfNeighbors()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.dbscan.getNeighbors.Data parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.dbscan.getNeighbors.Data) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string rowkey = 1;
      private java.lang.Object rowkey_ = "";
      /**
       * <code>required string rowkey = 1;</code>
       */
      public boolean hasRowkey() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string rowkey = 1;</code>
       */
      public java.lang.String getRowkey() {
        java.lang.Object ref = rowkey_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          rowkey_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string rowkey = 1;</code>
       */
      public com.google.protobuf.ByteString
          getRowkeyBytes() {
        java.lang.Object ref = rowkey_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          rowkey_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string rowkey = 1;</code>
       */
      public Builder setRowkey(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        rowkey_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string rowkey = 1;</code>
       */
      public Builder clearRowkey() {
        bitField0_ = (bitField0_ & ~0x00000001);
        rowkey_ = getDefaultInstance().getRowkey();
        onChanged();
        return this;
      }
      /**
       * <code>required string rowkey = 1;</code>
       */
      public Builder setRowkeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        rowkey_ = value;
        onChanged();
        return this;
      }

      // repeated double point = 2;
      private java.util.List<java.lang.Double> point_ = java.util.Collections.emptyList();
      private void ensurePointIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          point_ = new java.util.ArrayList<java.lang.Double>(point_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated double point = 2;</code>
       */
      public java.util.List<java.lang.Double>
          getPointList() {
        return java.util.Collections.unmodifiableList(point_);
      }
      /**
       * <code>repeated double point = 2;</code>
       */
      public int getPointCount() {
        return point_.size();
      }
      /**
       * <code>repeated double point = 2;</code>
       */
      public double getPoint(int index) {
        return point_.get(index);
      }
      /**
       * <code>repeated double point = 2;</code>
       */
      public Builder setPoint(
          int index, double value) {
        ensurePointIsMutable();
        point_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated double point = 2;</code>
       */
      public Builder addPoint(double value) {
        ensurePointIsMutable();
        point_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated double point = 2;</code>
       */
      public Builder addAllPoint(
          java.lang.Iterable<? extends java.lang.Double> values) {
        ensurePointIsMutable();
        super.addAll(values, point_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated double point = 2;</code>
       */
      public Builder clearPoint() {
        point_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }

      // required int32 clusterid = 3 [default = 0];
      private int clusterid_ ;
      /**
       * <code>required int32 clusterid = 3 [default = 0];</code>
       */
      public boolean hasClusterid() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int32 clusterid = 3 [default = 0];</code>
       */
      public int getClusterid() {
        return clusterid_;
      }
      /**
       * <code>required int32 clusterid = 3 [default = 0];</code>
       */
      public Builder setClusterid(int value) {
        bitField0_ |= 0x00000004;
        clusterid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 clusterid = 3 [default = 0];</code>
       */
      public Builder clearClusterid() {
        bitField0_ = (bitField0_ & ~0x00000004);
        clusterid_ = 0;
        onChanged();
        return this;
      }

      // required int32 numOfNeighbors = 4 [default = 1];
      private int numOfNeighbors_ = 1;
      /**
       * <code>required int32 numOfNeighbors = 4 [default = 1];</code>
       */
      public boolean hasNumOfNeighbors() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required int32 numOfNeighbors = 4 [default = 1];</code>
       */
      public int getNumOfNeighbors() {
        return numOfNeighbors_;
      }
      /**
       * <code>required int32 numOfNeighbors = 4 [default = 1];</code>
       */
      public Builder setNumOfNeighbors(int value) {
        bitField0_ |= 0x00000008;
        numOfNeighbors_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 numOfNeighbors = 4 [default = 1];</code>
       */
      public Builder clearNumOfNeighbors() {
        bitField0_ = (bitField0_ & ~0x00000008);
        numOfNeighbors_ = 1;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Data)
    }

    static {
      defaultInstance = new Data(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Data)
  }

  public interface getNeighborsResponseOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated .Data datas = 1;
    /**
     * <code>repeated .Data datas = 1;</code>
     */
    java.util.List<org.dbscan.getNeighbors.Data> 
        getDatasList();
    /**
     * <code>repeated .Data datas = 1;</code>
     */
    org.dbscan.getNeighbors.Data getDatas(int index);
    /**
     * <code>repeated .Data datas = 1;</code>
     */
    int getDatasCount();
    /**
     * <code>repeated .Data datas = 1;</code>
     */
    java.util.List<? extends org.dbscan.getNeighbors.DataOrBuilder> 
        getDatasOrBuilderList();
    /**
     * <code>repeated .Data datas = 1;</code>
     */
    org.dbscan.getNeighbors.DataOrBuilder getDatasOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code getNeighborsResponse}
   */
  public static final class getNeighborsResponse extends
      com.google.protobuf.GeneratedMessage
      implements getNeighborsResponseOrBuilder {
    // Use getNeighborsResponse.newBuilder() to construct.
    private getNeighborsResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private getNeighborsResponse(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final getNeighborsResponse defaultInstance;
    public static getNeighborsResponse getDefaultInstance() {
      return defaultInstance;
    }

    public getNeighborsResponse getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private getNeighborsResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                datas_ = new java.util.ArrayList<org.dbscan.getNeighbors.Data>();
                mutable_bitField0_ |= 0x00000001;
              }
              datas_.add(input.readMessage(org.dbscan.getNeighbors.Data.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          datas_ = java.util.Collections.unmodifiableList(datas_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.dbscan.getNeighbors.internal_static_getNeighborsResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.dbscan.getNeighbors.internal_static_getNeighborsResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.dbscan.getNeighbors.getNeighborsResponse.class, org.dbscan.getNeighbors.getNeighborsResponse.Builder.class);
    }

    public static com.google.protobuf.Parser<getNeighborsResponse> PARSER =
        new com.google.protobuf.AbstractParser<getNeighborsResponse>() {
      public getNeighborsResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new getNeighborsResponse(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<getNeighborsResponse> getParserForType() {
      return PARSER;
    }

    // repeated .Data datas = 1;
    public static final int DATAS_FIELD_NUMBER = 1;
    private java.util.List<org.dbscan.getNeighbors.Data> datas_;
    /**
     * <code>repeated .Data datas = 1;</code>
     */
    public java.util.List<org.dbscan.getNeighbors.Data> getDatasList() {
      return datas_;
    }
    /**
     * <code>repeated .Data datas = 1;</code>
     */
    public java.util.List<? extends org.dbscan.getNeighbors.DataOrBuilder> 
        getDatasOrBuilderList() {
      return datas_;
    }
    /**
     * <code>repeated .Data datas = 1;</code>
     */
    public int getDatasCount() {
      return datas_.size();
    }
    /**
     * <code>repeated .Data datas = 1;</code>
     */
    public org.dbscan.getNeighbors.Data getDatas(int index) {
      return datas_.get(index);
    }
    /**
     * <code>repeated .Data datas = 1;</code>
     */
    public org.dbscan.getNeighbors.DataOrBuilder getDatasOrBuilder(
        int index) {
      return datas_.get(index);
    }

    private void initFields() {
      datas_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      for (int i = 0; i < getDatasCount(); i++) {
        if (!getDatas(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < datas_.size(); i++) {
        output.writeMessage(1, datas_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < datas_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, datas_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.dbscan.getNeighbors.getNeighborsResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.dbscan.getNeighbors.getNeighborsResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.dbscan.getNeighbors.getNeighborsResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.dbscan.getNeighbors.getNeighborsResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.dbscan.getNeighbors.getNeighborsResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.dbscan.getNeighbors.getNeighborsResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.dbscan.getNeighbors.getNeighborsResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.dbscan.getNeighbors.getNeighborsResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.dbscan.getNeighbors.getNeighborsResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.dbscan.getNeighbors.getNeighborsResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.dbscan.getNeighbors.getNeighborsResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code getNeighborsResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.dbscan.getNeighbors.getNeighborsResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.dbscan.getNeighbors.internal_static_getNeighborsResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.dbscan.getNeighbors.internal_static_getNeighborsResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.dbscan.getNeighbors.getNeighborsResponse.class, org.dbscan.getNeighbors.getNeighborsResponse.Builder.class);
      }

      // Construct using org.dbscan.getNeighbors.getNeighborsResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getDatasFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (datasBuilder_ == null) {
          datas_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          datasBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.dbscan.getNeighbors.internal_static_getNeighborsResponse_descriptor;
      }

      public org.dbscan.getNeighbors.getNeighborsResponse getDefaultInstanceForType() {
        return org.dbscan.getNeighbors.getNeighborsResponse.getDefaultInstance();
      }

      public org.dbscan.getNeighbors.getNeighborsResponse build() {
        org.dbscan.getNeighbors.getNeighborsResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.dbscan.getNeighbors.getNeighborsResponse buildPartial() {
        org.dbscan.getNeighbors.getNeighborsResponse result = new org.dbscan.getNeighbors.getNeighborsResponse(this);
        int from_bitField0_ = bitField0_;
        if (datasBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            datas_ = java.util.Collections.unmodifiableList(datas_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.datas_ = datas_;
        } else {
          result.datas_ = datasBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.dbscan.getNeighbors.getNeighborsResponse) {
          return mergeFrom((org.dbscan.getNeighbors.getNeighborsResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.dbscan.getNeighbors.getNeighborsResponse other) {
        if (other == org.dbscan.getNeighbors.getNeighborsResponse.getDefaultInstance()) return this;
        if (datasBuilder_ == null) {
          if (!other.datas_.isEmpty()) {
            if (datas_.isEmpty()) {
              datas_ = other.datas_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureDatasIsMutable();
              datas_.addAll(other.datas_);
            }
            onChanged();
          }
        } else {
          if (!other.datas_.isEmpty()) {
            if (datasBuilder_.isEmpty()) {
              datasBuilder_.dispose();
              datasBuilder_ = null;
              datas_ = other.datas_;
              bitField0_ = (bitField0_ & ~0x00000001);
              datasBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getDatasFieldBuilder() : null;
            } else {
              datasBuilder_.addAllMessages(other.datas_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getDatasCount(); i++) {
          if (!getDatas(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.dbscan.getNeighbors.getNeighborsResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.dbscan.getNeighbors.getNeighborsResponse) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated .Data datas = 1;
      private java.util.List<org.dbscan.getNeighbors.Data> datas_ =
        java.util.Collections.emptyList();
      private void ensureDatasIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          datas_ = new java.util.ArrayList<org.dbscan.getNeighbors.Data>(datas_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          org.dbscan.getNeighbors.Data, org.dbscan.getNeighbors.Data.Builder, org.dbscan.getNeighbors.DataOrBuilder> datasBuilder_;

      /**
       * <code>repeated .Data datas = 1;</code>
       */
      public java.util.List<org.dbscan.getNeighbors.Data> getDatasList() {
        if (datasBuilder_ == null) {
          return java.util.Collections.unmodifiableList(datas_);
        } else {
          return datasBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Data datas = 1;</code>
       */
      public int getDatasCount() {
        if (datasBuilder_ == null) {
          return datas_.size();
        } else {
          return datasBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Data datas = 1;</code>
       */
      public org.dbscan.getNeighbors.Data getDatas(int index) {
        if (datasBuilder_ == null) {
          return datas_.get(index);
        } else {
          return datasBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Data datas = 1;</code>
       */
      public Builder setDatas(
          int index, org.dbscan.getNeighbors.Data value) {
        if (datasBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDatasIsMutable();
          datas_.set(index, value);
          onChanged();
        } else {
          datasBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Data datas = 1;</code>
       */
      public Builder setDatas(
          int index, org.dbscan.getNeighbors.Data.Builder builderForValue) {
        if (datasBuilder_ == null) {
          ensureDatasIsMutable();
          datas_.set(index, builderForValue.build());
          onChanged();
        } else {
          datasBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Data datas = 1;</code>
       */
      public Builder addDatas(org.dbscan.getNeighbors.Data value) {
        if (datasBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDatasIsMutable();
          datas_.add(value);
          onChanged();
        } else {
          datasBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Data datas = 1;</code>
       */
      public Builder addDatas(
          int index, org.dbscan.getNeighbors.Data value) {
        if (datasBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDatasIsMutable();
          datas_.add(index, value);
          onChanged();
        } else {
          datasBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Data datas = 1;</code>
       */
      public Builder addDatas(
          org.dbscan.getNeighbors.Data.Builder builderForValue) {
        if (datasBuilder_ == null) {
          ensureDatasIsMutable();
          datas_.add(builderForValue.build());
          onChanged();
        } else {
          datasBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Data datas = 1;</code>
       */
      public Builder addDatas(
          int index, org.dbscan.getNeighbors.Data.Builder builderForValue) {
        if (datasBuilder_ == null) {
          ensureDatasIsMutable();
          datas_.add(index, builderForValue.build());
          onChanged();
        } else {
          datasBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Data datas = 1;</code>
       */
      public Builder addAllDatas(
          java.lang.Iterable<? extends org.dbscan.getNeighbors.Data> values) {
        if (datasBuilder_ == null) {
          ensureDatasIsMutable();
          super.addAll(values, datas_);
          onChanged();
        } else {
          datasBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Data datas = 1;</code>
       */
      public Builder clearDatas() {
        if (datasBuilder_ == null) {
          datas_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          datasBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Data datas = 1;</code>
       */
      public Builder removeDatas(int index) {
        if (datasBuilder_ == null) {
          ensureDatasIsMutable();
          datas_.remove(index);
          onChanged();
        } else {
          datasBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Data datas = 1;</code>
       */
      public org.dbscan.getNeighbors.Data.Builder getDatasBuilder(
          int index) {
        return getDatasFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Data datas = 1;</code>
       */
      public org.dbscan.getNeighbors.DataOrBuilder getDatasOrBuilder(
          int index) {
        if (datasBuilder_ == null) {
          return datas_.get(index);  } else {
          return datasBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Data datas = 1;</code>
       */
      public java.util.List<? extends org.dbscan.getNeighbors.DataOrBuilder> 
           getDatasOrBuilderList() {
        if (datasBuilder_ != null) {
          return datasBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(datas_);
        }
      }
      /**
       * <code>repeated .Data datas = 1;</code>
       */
      public org.dbscan.getNeighbors.Data.Builder addDatasBuilder() {
        return getDatasFieldBuilder().addBuilder(
            org.dbscan.getNeighbors.Data.getDefaultInstance());
      }
      /**
       * <code>repeated .Data datas = 1;</code>
       */
      public org.dbscan.getNeighbors.Data.Builder addDatasBuilder(
          int index) {
        return getDatasFieldBuilder().addBuilder(
            index, org.dbscan.getNeighbors.Data.getDefaultInstance());
      }
      /**
       * <code>repeated .Data datas = 1;</code>
       */
      public java.util.List<org.dbscan.getNeighbors.Data.Builder> 
           getDatasBuilderList() {
        return getDatasFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          org.dbscan.getNeighbors.Data, org.dbscan.getNeighbors.Data.Builder, org.dbscan.getNeighbors.DataOrBuilder> 
          getDatasFieldBuilder() {
        if (datasBuilder_ == null) {
          datasBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              org.dbscan.getNeighbors.Data, org.dbscan.getNeighbors.Data.Builder, org.dbscan.getNeighbors.DataOrBuilder>(
                  datas_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          datas_ = null;
        }
        return datasBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:getNeighborsResponse)
    }

    static {
      defaultInstance = new getNeighborsResponse(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:getNeighborsResponse)
  }

  /**
   * Protobuf service {@code dbscanService}
   */
  public static abstract class dbscanService
      implements com.google.protobuf.Service {
    protected dbscanService() {}

    public interface Interface {
      /**
       * <code>rpc getNeighbours(.getNeighborsRequest) returns (.getNeighborsResponse);</code>
       */
      public abstract void getNeighbours(
          com.google.protobuf.RpcController controller,
          org.dbscan.getNeighbors.getNeighborsRequest request,
          com.google.protobuf.RpcCallback<org.dbscan.getNeighbors.getNeighborsResponse> done);

    }

    public static com.google.protobuf.Service newReflectiveService(
        final Interface impl) {
      return new dbscanService() {
        @java.lang.Override
        public  void getNeighbours(
            com.google.protobuf.RpcController controller,
            org.dbscan.getNeighbors.getNeighborsRequest request,
            com.google.protobuf.RpcCallback<org.dbscan.getNeighbors.getNeighborsResponse> done) {
          impl.getNeighbours(controller, request, done);
        }

      };
    }

    public static com.google.protobuf.BlockingService
        newReflectiveBlockingService(final BlockingInterface impl) {
      return new com.google.protobuf.BlockingService() {
        public final com.google.protobuf.Descriptors.ServiceDescriptor
            getDescriptorForType() {
          return getDescriptor();
        }

        public final com.google.protobuf.Message callBlockingMethod(
            com.google.protobuf.Descriptors.MethodDescriptor method,
            com.google.protobuf.RpcController controller,
            com.google.protobuf.Message request)
            throws com.google.protobuf.ServiceException {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.callBlockingMethod() given method descriptor for " +
              "wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return impl.getNeighbours(controller, (org.dbscan.getNeighbors.getNeighborsRequest)request);
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

        public final com.google.protobuf.Message
            getRequestPrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getRequestPrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return org.dbscan.getNeighbors.getNeighborsRequest.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

        public final com.google.protobuf.Message
            getResponsePrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getResponsePrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return org.dbscan.getNeighbors.getNeighborsResponse.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

      };
    }

    /**
     * <code>rpc getNeighbours(.getNeighborsRequest) returns (.getNeighborsResponse);</code>
     */
    public abstract void getNeighbours(
        com.google.protobuf.RpcController controller,
        org.dbscan.getNeighbors.getNeighborsRequest request,
        com.google.protobuf.RpcCallback<org.dbscan.getNeighbors.getNeighborsResponse> done);

    public static final
        com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptor() {
      return org.dbscan.getNeighbors.getDescriptor().getServices().get(0);
    }
    public final com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }

    public final void callMethod(
        com.google.protobuf.Descriptors.MethodDescriptor method,
        com.google.protobuf.RpcController controller,
        com.google.protobuf.Message request,
        com.google.protobuf.RpcCallback<
          com.google.protobuf.Message> done) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.callMethod() given method descriptor for wrong " +
          "service type.");
      }
      switch(method.getIndex()) {
        case 0:
          this.getNeighbours(controller, (org.dbscan.getNeighbors.getNeighborsRequest)request,
            com.google.protobuf.RpcUtil.<org.dbscan.getNeighbors.getNeighborsResponse>specializeCallback(
              done));
          return;
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public final com.google.protobuf.Message
        getRequestPrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getRequestPrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return org.dbscan.getNeighbors.getNeighborsRequest.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public final com.google.protobuf.Message
        getResponsePrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getResponsePrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return org.dbscan.getNeighbors.getNeighborsResponse.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public static Stub newStub(
        com.google.protobuf.RpcChannel channel) {
      return new Stub(channel);
    }

    public static final class Stub extends org.dbscan.getNeighbors.dbscanService implements Interface {
      private Stub(com.google.protobuf.RpcChannel channel) {
        this.channel = channel;
      }

      private final com.google.protobuf.RpcChannel channel;

      public com.google.protobuf.RpcChannel getChannel() {
        return channel;
      }

      public  void getNeighbours(
          com.google.protobuf.RpcController controller,
          org.dbscan.getNeighbors.getNeighborsRequest request,
          com.google.protobuf.RpcCallback<org.dbscan.getNeighbors.getNeighborsResponse> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          org.dbscan.getNeighbors.getNeighborsResponse.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            org.dbscan.getNeighbors.getNeighborsResponse.class,
            org.dbscan.getNeighbors.getNeighborsResponse.getDefaultInstance()));
      }
    }

    public static BlockingInterface newBlockingStub(
        com.google.protobuf.BlockingRpcChannel channel) {
      return new BlockingStub(channel);
    }

    public interface BlockingInterface {
      public org.dbscan.getNeighbors.getNeighborsResponse getNeighbours(
          com.google.protobuf.RpcController controller,
          org.dbscan.getNeighbors.getNeighborsRequest request)
          throws com.google.protobuf.ServiceException;
    }

    private static final class BlockingStub implements BlockingInterface {
      private BlockingStub(com.google.protobuf.BlockingRpcChannel channel) {
        this.channel = channel;
      }

      private final com.google.protobuf.BlockingRpcChannel channel;

      public org.dbscan.getNeighbors.getNeighborsResponse getNeighbours(
          com.google.protobuf.RpcController controller,
          org.dbscan.getNeighbors.getNeighborsRequest request)
          throws com.google.protobuf.ServiceException {
        return (org.dbscan.getNeighbors.getNeighborsResponse) channel.callBlockingMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          org.dbscan.getNeighbors.getNeighborsResponse.getDefaultInstance());
      }

    }

    // @@protoc_insertion_point(class_scope:dbscanService)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_getNeighborsRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_getNeighborsRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Data_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Data_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_getNeighborsResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_getNeighborsResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022getNeighbors.proto\"3\n\023getNeighborsRequ" +
      "est\022\016\n\003Eps\030\001 \002(\001:\0011\022\014\n\004data\030\002 \003(\001\"V\n\004Dat" +
      "a\022\016\n\006rowkey\030\001 \002(\t\022\r\n\005point\030\002 \003(\001\022\024\n\tclus" +
      "terid\030\003 \002(\005:\0010\022\031\n\016numOfNeighbors\030\004 \002(\005:\001" +
      "1\",\n\024getNeighborsResponse\022\024\n\005datas\030\001 \003(\013" +
      "2\005.Data2M\n\rdbscanService\022<\n\rgetNeighbour" +
      "s\022\024.getNeighborsRequest\032\025.getNeighborsRe" +
      "sponseB\037\n\norg.dbscanB\014getNeighborsH\001\210\001\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_getNeighborsRequest_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_getNeighborsRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_getNeighborsRequest_descriptor,
              new java.lang.String[] { "Eps", "Data", });
          internal_static_Data_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_Data_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Data_descriptor,
              new java.lang.String[] { "Rowkey", "Point", "Clusterid", "NumOfNeighbors", });
          internal_static_getNeighborsResponse_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_getNeighborsResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_getNeighborsResponse_descriptor,
              new java.lang.String[] { "Datas", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
